// Code generated by "stringer -type=LogMessageType -trimprefix=Log -output=types_stringer_log.go"; DO NOT EDIT.

package daemon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogLast-1634497651]
	_ = x[LogError-1668838512]
	_ = x[LogNext-1869376871]
	_ = x[LogRead-1684108385]
	_ = x[LogWrite-1684108310]
	_ = x[LogStartActivity-1398035028]
	_ = x[LogStopActivity-1398034256]
	_ = x[LogResult-1381190740]
}

const (
	_LogMessageType_name_0 = "Result"
	_LogMessageType_name_1 = "StopActivity"
	_LogMessageType_name_2 = "StartActivity"
	_LogMessageType_name_3 = "Last"
	_LogMessageType_name_4 = "Error"
	_LogMessageType_name_5 = "Write"
	_LogMessageType_name_6 = "Read"
	_LogMessageType_name_7 = "Next"
)

func (i LogMessageType) String() string {
	switch {
	case i == 1381190740:
		return _LogMessageType_name_0
	case i == 1398034256:
		return _LogMessageType_name_1
	case i == 1398035028:
		return _LogMessageType_name_2
	case i == 1634497651:
		return _LogMessageType_name_3
	case i == 1668838512:
		return _LogMessageType_name_4
	case i == 1684108310:
		return _LogMessageType_name_5
	case i == 1684108385:
		return _LogMessageType_name_6
	case i == 1869376871:
		return _LogMessageType_name_7
	default:
		return "LogMessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
