// Code generated by "stringer -type=Verbosity -trimprefix=Verb -output=types_stringer_verbosity.go"; DO NOT EDIT.

package daemon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VerbError-0]
	_ = x[VerbWarn-1]
	_ = x[VerbNotice-2]
	_ = x[VerbInfo-3]
	_ = x[VerbTalkative-4]
	_ = x[VerbChatty-5]
	_ = x[VerbDebug-6]
	_ = x[VerbVomit-7]
}

const _Verbosity_name = "ErrorWarnNoticeInfoTalkativeChattyDebugVomit"

var _Verbosity_index = [...]uint8{0, 5, 9, 15, 19, 28, 34, 39, 44}

func (i Verbosity) String() string {
	if i >= Verbosity(len(_Verbosity_index)-1) {
		return "Verbosity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Verbosity_name[_Verbosity_index[i]:_Verbosity_index[i+1]]
}
