// Code generated by "stringer -type=Operation -trimprefix=Op -output=types_stringer_operation.go"; DO NOT EDIT.

package daemon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpIsValidPath-1]
	_ = x[OpQueryReferrers-6]
	_ = x[OpAddToStore-7]
	_ = x[OpBuildPaths-9]
	_ = x[OpEnsurePath-10]
	_ = x[OpAddTempRoot-11]
	_ = x[OpAddIndirectRoot-12]
	_ = x[OpFindRoots-14]
	_ = x[OpSetOptions-19]
	_ = x[OpCollectGarbage-20]
	_ = x[OpQueryAllValidPaths-23]
	_ = x[OpQueryPathInfo-26]
	_ = x[OpQueryPathFromHashPart-29]
	_ = x[OpQuerySubstitutablePathInfos-30]
	_ = x[OpQueryValidPaths-31]
	_ = x[OpQuerySubstitutablePaths-32]
	_ = x[OpQueryValidDerivers-33]
	_ = x[OpOptimiseStore-34]
	_ = x[OpVerifyStore-35]
	_ = x[OpBuildDerivation-36]
	_ = x[OpAddSignatures-37]
	_ = x[OpNarFromPath-38]
	_ = x[OpAddToStoreNar-39]
	_ = x[OpQueryMissing-40]
	_ = x[OpQueryDerivationOutputMap-41]
	_ = x[OpRegisterDrvOutput-42]
	_ = x[OpQueryRealisation-43]
	_ = x[OpAddMultipleToStore-44]
	_ = x[OpAddBuildLog-45]
	_ = x[OpBuildPathsWithResults-46]
	_ = x[OpAddPermRoot-47]
}

const (
	_Operation_name_0 = "IsValidPath"
	_Operation_name_1 = "QueryReferrersAddToStore"
	_Operation_name_2 = "BuildPathsEnsurePathAddTempRootAddIndirectRoot"
	_Operation_name_3 = "FindRoots"
	_Operation_name_4 = "SetOptionsCollectGarbage"
	_Operation_name_5 = "QueryAllValidPaths"
	_Operation_name_6 = "QueryPathInfo"
	_Operation_name_7 = "QueryPathFromHashPartQuerySubstitutablePathInfosQueryValidPathsQuerySubstitutablePathsQueryValidDeriversOptimiseStoreVerifyStoreBuildDerivationAddSignaturesNarFromPathAddToStoreNarQueryMissingQueryDerivationOutputMapRegisterDrvOutputQueryRealisationAddMultipleToStoreAddBuildLogBuildPathsWithResultsAddPermRoot"
)

var (
	_Operation_index_1 = [...]uint8{0, 14, 24}
	_Operation_index_2 = [...]uint8{0, 10, 20, 31, 46}
	_Operation_index_4 = [...]uint8{0, 10, 24}
	_Operation_index_7 = [...]uint16{0, 21, 48, 63, 86, 104, 117, 128, 143, 156, 167, 180, 192, 216, 233, 249, 267, 278, 299, 310}
)

func (i Operation) String() string {
	switch {
	case i == 1:
		return _Operation_name_0
	case 6 <= i && i <= 7:
		i -= 6
		return _Operation_name_1[_Operation_index_1[i]:_Operation_index_1[i+1]]
	case 9 <= i && i <= 12:
		i -= 9
		return _Operation_name_2[_Operation_index_2[i]:_Operation_index_2[i+1]]
	case i == 14:
		return _Operation_name_3
	case 19 <= i && i <= 20:
		i -= 19
		return _Operation_name_4[_Operation_index_4[i]:_Operation_index_4[i+1]]
	case i == 23:
		return _Operation_name_5
	case i == 26:
		return _Operation_name_6
	case 29 <= i && i <= 47:
		i -= 29
		return _Operation_name_7[_Operation_index_7[i]:_Operation_index_7[i+1]]
	default:
		return "Operation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
