// Code generated by "stringer -type=BuildMode -trimprefix=BuildMode -output=types_stringer_buildmode.go"; DO NOT EDIT.

package daemon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BuildModeNormal-0]
	_ = x[BuildModeRepair-1]
	_ = x[BuildModeCheck-2]
}

const _BuildMode_name = "NormalRepairCheck"

var _BuildMode_index = [...]uint8{0, 6, 12, 17}

func (i BuildMode) String() string {
	if i >= BuildMode(len(_BuildMode_index)-1) {
		return "BuildMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BuildMode_name[_BuildMode_index[i]:_BuildMode_index[i+1]]
}
