// Code generated by "stringer -type=ActivityType -trimprefix=Act -output=types_stringer_activity.go"; DO NOT EDIT.

package daemon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActUnknown-0]
	_ = x[ActCopyPath-100]
	_ = x[ActFileTransfer-101]
	_ = x[ActRealise-102]
	_ = x[ActCopyPaths-103]
	_ = x[ActBuilds-104]
	_ = x[ActBuild-105]
	_ = x[ActOptimiseStore-106]
	_ = x[ActVerifyPaths-107]
	_ = x[ActSubstitute-108]
	_ = x[ActQueryPathInfo-109]
	_ = x[ActPostBuildHook-110]
	_ = x[ActBuildWaiting-111]
	_ = x[ActFetchTree-112]
}

const (
	_ActivityType_name_0 = "Unknown"
	_ActivityType_name_1 = "CopyPathFileTransferRealiseCopyPathsBuildsBuildOptimiseStoreVerifyPathsSubstituteQueryPathInfoPostBuildHookBuildWaitingFetchTree"
)

var (
	_ActivityType_index_1 = [...]uint8{0, 8, 20, 27, 36, 42, 47, 60, 71, 81, 94, 107, 119, 128}
)

func (i ActivityType) String() string {
	switch {
	case i == 0:
		return _ActivityType_name_0
	case 100 <= i && i <= 112:
		i -= 100
		return _ActivityType_name_1[_ActivityType_index_1[i]:_ActivityType_index_1[i+1]]
	default:
		return "ActivityType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
