// Code generated by "stringer -type=TrustLevel -trimprefix=Trust -output=types_stringer_trust.go"; DO NOT EDIT.

package daemon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TrustUnknown-0]
	_ = x[TrustTrusted-1]
	_ = x[TrustNotTrusted-2]
}

const _TrustLevel_name = "UnknownTrustedNotTrusted"

var _TrustLevel_index = [...]uint8{0, 7, 14, 24}

func (i TrustLevel) String() string {
	if i >= TrustLevel(len(_TrustLevel_index)-1) {
		return "TrustLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TrustLevel_name[_TrustLevel_index[i]:_TrustLevel_index[i+1]]
}
