// Code generated by "stringer -type=BuildStatus -trimprefix=BuildStatus -output=types_stringer_buildstatus.go"; DO NOT EDIT.

package daemon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BuildStatusBuilt-0]
	_ = x[BuildStatusSubstituted-1]
	_ = x[BuildStatusAlreadyValid-2]
	_ = x[BuildStatusPermanentFailure-3]
	_ = x[BuildStatusInputRejected-4]
	_ = x[BuildStatusOutputRejected-5]
	_ = x[BuildStatusTransientFailure-6]
	_ = x[BuildStatusCachedFailure-7]
	_ = x[BuildStatusTimedOut-8]
	_ = x[BuildStatusMiscFailure-9]
	_ = x[BuildStatusDependencyFailed-10]
	_ = x[BuildStatusLogLimitExceeded-11]
	_ = x[BuildStatusNotDeterministic-12]
	_ = x[BuildStatusResolvesToAlreadyValid-13]
	_ = x[BuildStatusNoSubstituters-14]
}

const _BuildStatus_name = "BuiltSubstitutedAlreadyValidPermanentFailureInputRejectedOutputRejectedTransientFailureCachedFailureTimedOutMiscFailureDependencyFailedLogLimitExceededNotDeterministicResolvesToAlreadyValidNoSubstituters"

var _BuildStatus_index = [...]uint8{0, 5, 16, 28, 44, 57, 71, 87, 100, 108, 119, 135, 151, 167, 189, 203}

func (i BuildStatus) String() string {
	if i >= BuildStatus(len(_BuildStatus_index)-1) {
		return "BuildStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BuildStatus_name[_BuildStatus_index[i]:_BuildStatus_index[i+1]]
}
