// Code generated by "stringer -type=GCAction -trimprefix=GC -output=types_stringer_gc.go"; DO NOT EDIT.

package daemon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GCReturnLive-0]
	_ = x[GCReturnDead-1]
	_ = x[GCDeleteDead-2]
	_ = x[GCDeleteSpecific-3]
}

const _GCAction_name = "ReturnLiveReturnDeadDeleteDeadDeleteSpecific"

var _GCAction_index = [...]uint8{0, 10, 20, 30, 44}

func (i GCAction) String() string {
	if i >= GCAction(len(_GCAction_index)-1) {
		return "GCAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GCAction_name[_GCAction_index[i]:_GCAction_index[i+1]]
}
